#!/bin/bash

#Old method first, feel free to remove prior to deployment

#cd /Users/Shared/jamfdata/log/Connect/Service/
#mostRecentLogFile=$(ls -Art | tail -n 1)
#
##echo "$mostRecentLogFile"
#
#connectorID=$(grep -ai "Connector ID : "  $mostRecentLogFile | head -n1)
#
#result=$(echo $connectorID | awk '{print $6}')
#
#echo "<result>$result</result>"


#New method that reads deviceID from PPPC profile.

#DeviceId of MacOS Jamf Remote Assist Session

deviceID=$(sudo profiles show -output stdout-xml | grep -I deviceId=)

trimDeviceId=$(echo ${deviceID##*=})

echo "<result>$trimDeviceId</result>"
